excel_merge/urls.py
#!/usr/bin/env python
# encoding: utf-8
"""
    @author: madgd
    @license: (C) Copyright 2020-2021 madgd. All Rights Reserved.
    @contact: madgdtju@gmail.com
    @software: 
    @file: urls.py
    @time: 2020/10/29 10:05 上午
    @desc:
"""
from django.urls import path

from . import views

app_name = "excel_merge"
urlpatterns = [
    path('', views.index, name='index'),
    path('merge/', views.merge, name='merge')
]

index/urls.py
#!/usr/bin/env python
# encoding: utf-8
"""
    @author: madgd
    @license: (C) Copyright 2020-2021 madgd. All Rights Reserved.
    @contact: madgdtju@gmail.com
    @software: 
    @file: urls.py
    @time: 2020/10/23 2:06 下午
    @desc:
"""
from django.urls import path

from . import views

app_name = "index"
urlpatterns = [
    path('', views.index, name='index'),
]

toolhub/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url, include
import notice_manage.urls
from django.views.generic import TemplateView

urlpatterns = [
    # path('', include('index.urls')),
    path('admin/', admin.site.urls),
    path('excel_split/', include('excel_split.urls')),
    path('excel_merge/', include('excel_merge.urls')),
    url(r'^api/', include(notice_manage.urls)),
    url(r'^$', TemplateView.as_view(template_name="index.html")),
]

excel_merge/models.py
from django.db import models

# Create your models here.

excel_merge/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse, FileResponse
# from django.views import generic
from django.shortcuts import render
import sys
import os
sys.path.append(os.path.dirname(os.path.abspath(__file__)) + "/../../")
from exceltools.excel_merger.excel_merger import excelMergeBySheet
from django import forms
import time
from os.path import basename


def handle_uploaded_files(files, key):
    path = ""
    for f in files:
        if not key in f.name:
            continue
        # todo: check excel
        if not path:
            path = "./excel_merge/upload/%s_etc_merged_%s" % (basename(".".join(f.name.split(".")[:-1])),
                                                              time.strftime("%Y_%m_%d-%H_%M", time.localtime()))
            if not os.path.exists(path):
                os.mkdir(path)
        with open("%s/%s" % (path, f.name), 'wb+') as destination:
            for chunk in f.chunks():
                destination.write(chunk)
    return path

def index(request):
    template_name = 'excel_merge/index.html'
    context = {}
    return render(request, template_name, context)

class UploadFileForm(forms.Form):
    excel = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}))
    sheetNum = forms.NumberInput()
    sheetNameKey = forms.CharField(required=False)
    headLines = forms.NumberInput()
    excelNameKey = forms.CharField(max_length=50, required=False)
    # allSheet = forms.BooleanField(required=False)

def merge(request):
    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES)
        # print(request.FILES)
        # print(request.FILES.getlist('excel'))
        # return HttpResponse("form wrong")
        if form.is_valid():
            excelNameKey = request.POST['excelNameKey']
            # save excel
            savedExcels = handle_uploaded_files(request.FILES.getlist('excel'), excelNameKey)
            # print(savedExcels)
            # merge excel
            headLines = int(request.POST['headLines'])
            sheetNum = int(request.POST["sheetNum"])
            sheetNameKey = request.POST['sheetNameKey']
            allSheet = 'allSheet' in request.POST
            rmDup = 'rmDup' in request.POST
            styles = 'styles' in request.POST
            outputPath, err = excelMergeBySheet(savedExcels, headLines=headLines, sheetNum=sheetNum,
                                                sheetNameKey=sheetNameKey, allSheet=allSheet, rmDup=rmDup, styles=styles)
            # return file
            download_file = open(outputPath, 'rb')
            response = FileResponse(download_file)
            response['Content-Type'] = 'application/vnd.ms-excel'
            response['Content-Disposition'] = "attachment;filename=%s" % basename(outputPath).encode('utf-8').decode('ISO-8859-1')
            return response
        else:
            return HttpResponse("form wrong")
    else:
        return HttpResponse("need post")

excel_merge/templates/excel_merge/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <style type="text/css">
        table.gridtable td {
            border-width: 1px;
            border-style: solid;
            border-color: #666666;
            background-color: #ffffff;
        }
    </style>
    <meta charset="UTF-8">
    <!--设置过期时间设置0为直接过期并清除缓存-->
    <meta http-equiv="Expires" content="0">
    <!--设置不缓存页面-->
    <meta http-equiv="Pragma" content="no-cache">
    <!--设置不修改消息存储-->
    <meta http-equiv="Cache-Control" content="no-cache">
    <!--同上-->
    <meta http-equiv="Cache" content="no-cache">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="keywords" content="Excel多个表合并" />
    <meta name="description" content="本工具支持以下功能:Excel多个表合并，支持多sheet分别合并，操作如下：" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>多个表合并</title>

    {% load static %}

    <link rel="stylesheet" type="text/css" href="{% static 'excel_merge/style.css' %}">
</head>

<body class="linear">
    <h1>excel多表合并</h1>

    <h3 style="color:red">目前依赖库仅支持xlsx格式，xls格式可在本地另存为xlsx再进行操作</h3>
    <form action="{% url 'excel_merge:merge' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <b>把多个Excel文件：</b><input name="excel" type="file" multiple="multiple" /><br></br>
        <b>中，包含</b><input name="excelNameKey" type="text" value="" placeholder="默认全部"/>关键词的部分excel<br></br>
        <b>的第</b><input name="sheetNum" type="text" value="1" placeholder="1"/>个sheet</b>
        或者 名称关键词(匹配第一个命中)包含 <input name="sheetNameKey" type="text" />的sheet<br></br>
        <b>表头行数</b><input name="headLines" type="text" value="1" placeholder="1"/><b>(默认1)</b> <br></br>
        <input type="checkbox" name="rmDup" value="true"><b>
            按行去重
        </b></input>
        <input type="checkbox" name="allSheet" value="true"><b>
            按sheet位置合并全部表
        </b></input>
        <input type="checkbox" name="styles" checked><b>
            保留原表样式(不保留处理速度提升，默认保留)
        </b></input>
        <br></br>

        <input type="submit" value="合并">
    </form>
    <br></br>
    <div><a href="../">其他工具</a></div>
    <br></br>
    <p></p>
</body>

</html>