excel_split/urls.py
#!/usr/bin/env python
# encoding: utf-8
"""
    @author: madgd
    @license: (C) Copyright 2020-2021 madgd. All Rights Reserved.
    @contact: madgdtju@gmail.com
    @software: 
    @file: urls.py
    @time: 2020/10/22 6:02 下午
    @desc:
"""
from django.urls import path

from . import views

app_name = "excel_split"
urlpatterns = [
    path('', views.index, name='index'),
    path('split/', views.split, name='split')
]

index/urls.py
#!/usr/bin/env python
# encoding: utf-8
"""
    @author: madgd
    @license: (C) Copyright 2020-2021 madgd. All Rights Reserved.
    @contact: madgdtju@gmail.com
    @software: 
    @file: urls.py
    @time: 2020/10/23 2:06 下午
    @desc:
"""
from django.urls import path

from . import views

app_name = "index"
urlpatterns = [
    path('', views.index, name='index'),
]

toolhub/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url, include
import notice_manage.urls
from django.views.generic import TemplateView

urlpatterns = [
    # path('', include('index.urls')),
    path('admin/', admin.site.urls),
    path('excel_split/', include('excel_split.urls')),
    path('excel_merge/', include('excel_merge.urls')),
    url(r'^api/', include(notice_manage.urls)),
    url(r'^$', TemplateView.as_view(template_name="index.html")),
]

excel_split/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse, FileResponse
# from django.views import generic
from django.shortcuts import render
import sys
import os
sys.path.append(os.path.dirname(os.path.abspath(__file__)) + "/../../")
from exceltools.excel_spliter.excel_spliter import excelSplitBySheet
from django import forms
import zipfile
from os.path import basename


def handle_uploaded_file(f):
    with open("./excel_split/upload/%s" % f.name, 'wb+') as destination:
        for chunk in f.chunks():
            destination.write(chunk)
    return "./excel_split/upload/%s" % f.name

def index(request):
    template_name = 'excel_split/index.html'
    context = {}
    return render(request, template_name, context)

class UploadFileForm(forms.Form):
    excel = forms.FileField()
    sheetNum = forms.NumberInput()
    sheetNameKey = forms.CharField(required=False)
    headLines = forms.NumberInput()
    columnLabels = forms.CharField(max_length=50)
    # allSheet = forms.BooleanField(required=False)

def split(request):
    # print(request.POST)
    # print(request.FILES)
    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            # save excel
            savedExcel = handle_uploaded_file(request.FILES['excel'])
            print(savedExcel)
            # split excel
            columnLabels = request.POST['columnLabels']
            headLines = int(request.POST['headLines'])
            sheetNum = int(request.POST["sheetNum"])
            sheetNameKey = request.POST['sheetNameKey']
            allSheet = 'allSheet' in request.POST
            styles = 'styles' in request.POST
            print(styles)
            outputPath, err = excelSplitBySheet(savedExcel, columnLabels=columnLabels, headLines=headLines, \
                              sheetNum=sheetNum, sheetNameKey=sheetNameKey, allSheet=allSheet, styles=styles)
            print(outputPath)
            # zip excel
            zip_file = ".".join(savedExcel.split(".")[:-1]) + "_split_by_%s.zip" % columnLabels
            zip = zipfile.ZipFile(zip_file, 'w')
            for f in os.listdir(outputPath):
                zip.write(os.path.join(outputPath, f), f, zipfile.ZIP_DEFLATED)
            zip.close()
            # return zip file
            download_file = open(zip_file, 'rb')
            print(basename(zip_file))
            response = FileResponse(download_file)
            response['Content-Type'] = 'application/zip'
            response['Content-Disposition'] = "attachment;filename=%s" % basename(zip_file).encode('utf-8').decode('ISO-8859-1')
            return response
        else:
            return HttpResponse("form wrong")
    else:
        return HttpResponse("need post")

excel_split/templates/excel_split/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <style type="text/css">
        table.gridtable td {
            border-width: 1px;
            border-style: solid;
            border-color: #666666;
            background-color: #ffffff;
        }
    </style>
    <meta charset="UTF-8">
    <!--设置过期时间设置0为直接过期并清除缓存-->
    <meta http-equiv="Expires" content="0">
    <!--设置不缓存页面-->
    <meta http-equiv="Pragma" content="no-cache">
    <!--设置不修改消息存储-->
    <meta http-equiv="Cache-Control" content="no-cache">
    <!--同上-->
    <meta http-equiv="Cache" content="no-cache">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="keywords" content="Excel按列拆分成多个表,Excel按列拆分,Excel拆分成多个表" />
    <meta name="description" content="本工具支持以下功能:Excel按列拆分为多个表，操作如下：" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>按指定列拆分成多个表</title>

    {% load static %}

    <link rel="stylesheet" type="text/css" href="{% static 'excel_split/style.css' %}">
</head>

<body class="linear">
    <h1>按列拆分excel为多表</h1>

    <h3 style="color:red">目前依赖库仅支持xlsx格式，xls格式可在本地另存为xlsx再进行操作</h3>
    <form action="{% url 'excel_split:split' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <b>把Excel文件：</b><input name="excel" type="file" /><br></br>
        <b>的第</b><input name="sheetNum" type="text" value="1" placeholder="1"/>个sheet</b>
        或者 名称关键词(匹配第一个命中)包含 <input name="sheetNameKey" type="text" />的sheet<br></br>
        <b>表头行数</b><input name="headLines" type="text" value="1" placeholder="1"/><b>(默认1)</b> <br></br>
        <b>按第</b><input name="columnLabels" type="text" placeholder="A" value="A"/><b>列拆分成</b>(excel列号大写A、B、C...,如果多列用英文‘,’隔开，例如：A,B,C) <br></br>
        <input type="checkbox" name="allSheet" value="true"><b>
            按指定列名称自动匹配其他sheet中对应列，拆分整表(默认只拆分选定sheet)
        </b></input>
        <input type="checkbox" name="styles" checked><b>
            保留原表样式(不保留处理速度提升，默认保留)
        </b></input>
        <br>
        <br>

        <input type="submit" value="拆分">
    </form>
    <br></br>
    <div><a href="../">其他工具</a></div>
    <br></br>
    <p></p>
</body>

</html>